using System;
using Xunit;

namespace Calculator_test.TestProject1
{
    public class UnitTest1
    {
        [Fact]
        public void DivideTest()
        {
            
            double num1 = 1;
            double num2 = 0;
            double expectedResult = 0;

            double result = AutoGeneratedProgram
        }
    }
}
